name: github pages

on:
  push:
    branches:
      - bolghera

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm i
      - run: npm run build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          # Artifact name
          name: build # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: public/
          # The desired behavior if no files are found using the provided path.
      - name: Push directory to Github Pages
        uses: cpina/github-action-push-to-another-repository@v1.2
        with:
          source-directory: 'public'
          destination-github-username: 'ruggi99'
          destination-repository-name: 'ruggi99.github.io'
          user-email: 'ruggi99@github.com'
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      - name: FTP Deploy to Altervista
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.ruggi.altervista.org
          username: ${{ secrets.ALTERVISTA_US }}
          password: ${{ secrets.ALTERVISTA_PW }}
          local-dir: public/
          server-dir: /OBS/
          log-level: standard

